version: '3.8'
services:
  db:
      image: mysql:latest
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_DATABASE: pausekfet
      ports: 
        - "3307:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      restart: always
  app:
    image: pausekfet
    build:
      context: .
      dockerfile: API/Dockerfile
  
volumes:
  mysql_data:   